image:
  - Visual Studio 2019

configuration: Release

environment:
  matrix:
    - build_type: Win32

for:
  -
    matrix:
      only:
        - build_type: Win32
        - image: Visual Studio 2019
    environment:
      VCPKG_TRIPLET: x86-windows-static
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_GENERATOR_PLATFORM: Win32
    install:
      - cmd: vcpkg install sdl2:%VCPKG_TRIPLET%
      - cmd: vcpkg install libsndfile:%VCPKG_TRIPLET%
    before_build:
      - cmd: git submodule update --init --recursive
    build_script:
      - cmd: mkdir CMakeBuild
      - cmd: cd CMakeBuild
      - cmd: cmake -G"%CMAKE_GENERATOR%" -A"%CMAKE_GENERATOR_PLATFORM%" -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=%VCPKG_TRIPLET% -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      - cmd: cd ..
      - cmd: cmake --build CMakeBuild --config Release -j
